/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) throws Exception {
        ServerLauncherRF.main(new String[]{});
        //MemoryDataProcess.printProcessedData();
        Display.createsDisplay();
        GPUdata.getGPUdata();
    }
}
